"""Created shortened_urls table

Revision ID: 1ffab7343c61
Revises:
Create Date: 2025-04-30 18:29:36.229976

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1ffab7343c61"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "shortened_urls",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("short_key", sa.String(length=8), nullable=False),
        sa.Column("original_url", sa.String(length=2048), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("original_url"),
    )
    op.create_index(
        op.f("ix_shortened_urls_short_key"),
        "shortened_urls",
        ["short_key"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shortened_urls_short_key"), table_name="shortened_urls")
    op.drop_table("shortened_urls")
    # ### end Alembic commands ###
